export const posts = [
  {
    id: 1,
    title: "Test Post 1",
    email: "test@example.com",
    image: 1,
    userId: 1,
  },
  {
    id: 2,
    title: "Test Post 2",
    email: "test@example.com",
    image: 2,
    userId: 2,
  },
  {
    id: 3,
    title: "Test Post 3",
    email: "test@example.com",
    image: 3,
    userId: 3,
  },
  {
    id: 4,
    title: "Test Post 4",
    email: "test@example.com",
    image: 4,
    userId: 4,
  },
  {
    id: 5,
    title: "Test Post 5",
    email: "test@example.com",
    image: 5,
    userId: 5,
  },
  {
    id: 6,
    title: "Test Post 6",
    email: "test@example.com",
    image: 6,
    userId: 6,
  },
  {
    id: 7,
    title: "Test Post 7",
    email: "test@example.com",
    image: 7,
    userId: 7,
  },
  {
    id: 8,
    title: "Test Post 8",
    email: "test@example.com",
    image: 8,
    userId: 8,
  },
  {
    id: 9,
    title: "Test Post 9",
    email: "test@example.com",
    image: 9,
    userId: 9,
  },
  {
    id: 10,
    title: "Test Post 10",
    email: "test@example.com",
    image: 10,
    userId: 10,
  },
  {
    id: 11,
    title: "Test Post 11",
    email: "test@example.com",
    image: 11,
    userId: 11,
  },
  {
    id: 12,
    title: "Test Post 12",
    email: "test@example.com",
    image: 12,
    userId: 12,
  },
  {
    id: 13,
    title: "Test Post 13",
    email: "test@example.com",
    image: 13,
    userId: 13,
  },
  {
    id: 14,
    title: "Test Post 14",
    email: "test@example.com",
    image: 14,
    userId: 14,
  },
  {
    id: 15,
    title: "Test Post 15",
    email: "test@example.com",
    image: 15,
    userId: 15,
  },
  {
    id: 16,
    title: "Test Post 16",
    email: "test@example.com",
    image: 16,
    userId: 16,
  },
  {
    id: 17,
    title: "Test Post 17",
    email: "test@example.com",
    image: 17,
    userId: 17,
  },
  {
    id: 18,
    title: "Test Post 18",
    email: "test@example.com",
    image: 18,
    userId: 18,
  },
  {
    id: 19,
    title: "Test Post 19",
    email: "test@example.com",
    image: 19,
    userId: 19,
  },
  {
    id: 20,
    title: "Test Post 20",
    email: "test@example.com",
    image: 20,
    userId: 20,
  },
  {
    id: 21,
    title: "Test Post 21",
    email: "test@example.com",
    image: 21,
    userId: 21,
  },
  {
    id: 22,
    title: "Test Post 22",
    email: "test@example.com",
    image: 22,
    userId: 22,
  },
];
